### ISSUE TITLE
Can't find the nodes

### ISSUE THREAD

**Issue by bosbrand** [Clybius/ComfyUI-Latent-Modifiers#1]
Where do they show up? I installed using the manager. Searching also doesn't help.

**Comment by Xephobia** [comment]
Relevant warning message :
`Skip /home/gnuwu/ComfyUI/custom_nodes/sampler_mega_modifier.py module for custom nodes due to the lack of NODE_CLASS_MAPPINGS.`

**Comment by Clybius** [comment]
I believe this is an issue relating to the way Manager installs this repo. It seems to not be downloading the whole repo, but rather the Python file inside of it, as this was the original way to install the node. I've changed to a folder with `__init__.py` included.

To fix this problem, delete `custom_nodes/sampler_mega_modifier.py` if you see that it's the only file from this repo included in your `custom_nodes` folder. Then, inside of the `custom_nodes` do the following: `git clone "https://github.com/Clybius/ComfyUI-Latent-Modifiers"`

This ought to install the whole folder instead of the single Python file, then things should work. Let me know if there's any further issues!

**Comment by Clybius** [comment]
Since I presume this is fixed now (Thanks folks here and @ ComfyUI-Manager!), I'll be closing this.
